public class main {
    public static void main(String[] args) {
        BytePairEncoder bytePairEncoder = new BytePairEncoder("abcabfcabdcahrhrhbcabfcabcadgadgadgsbcabfcabcabgadacabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafcabcabcabasdagfcabcdabcabfcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabcabcabfcabdcabcabfcabcadbcabfcabfcabcabfcabcabcabfcabcdabcabfcabcabcabffcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabacabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcadsabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcdabcabfcabcabcabfcabdcabcabfcabcadbcabfcabcabcabfcabcabcabfcabcadabcabfcabc");
        System.out.println();
        bytePairEncoder.decode();
    }
}
